apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jt6g9li6b-go
  janus-idp.io/tekton: jt6g9li6b-go
  backstage.io/kubernetes-id: jt6g9li6b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jt6g9li6b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
